name: thesalesgong
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.3


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  http: ^1.2.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  audioplayers: ^5.2.1
  firebase_messaging: ^14.7.18
  awesome_notifications: ^0.9.2
  purchases_flutter: ^6.24.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0
  ffi: ^2.1.3
  win32: ^5.8.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/gong.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/


  
